### ISSUE TITLE
请问这个插件的功能和这个issue里提到的一样吗?

### ISSUE THREAD

**Issue by nobodxbodon** [cleverdango/vscode-pinyin#1]
就在刚才讨论组里的[这个演示](https://github.com/program-in-chinese/overview/issues/11#issuecomment-320431936)好像输入wenj就会提示"打开文件()"这个方法. 好奇这个插件的功能有何不同?

**Comment by cleverdango** [comment]
@nobodxbodon 是一样的！

**Comment by nobodxbodon** [comment]
多谢解惑 :)

**Comment by nobodxbodon** [comment]
不知你和 @lightrabbit 觉得把这个项目fork到讨论组里进行继续维护如何?

**Comment by lightrabbit** [comment]
我觉得挺好的，这样大家可以一起来维护，不过和这个项目相关的，还有
https://github.com/cleverdango/vscode
这个项目，上面这个里面就记录着对于vscode匹配算法修改的部分

**Comment by cleverdango** [comment]
没问题，自从vscode更新之后，就无法使用这个插件，确实需要大家定期维护

**Comment by nobodxbodon** [comment]
哦, 如果是有依赖关系的话, 感觉放在一起比较好. 这个改动程度比想象中的大呵. 
有空的话还请麻烦分享一下插件开发的教程(链接也好)和这个项目的大概实现思路, 好让有兴趣参与维护的新手入门的门槛低些. 多谢!

另外, 即使插件无效, 自动补全还是可以用吧, 只是要开中文输入法输入一两个中文了? 我现在eclipse里就是这样.

**Comment by cleverdango** [comment]
@nobodxbodon 可以的，确实我们在开发的过程中遇到了一些中国程序员才会遇到的坑：）

**Comment by nobodxbodon** [comment]
期待! 另外, 请你们挑方便的时候操刀fork吧, 感觉这个由原作者来比较合适和荣幸.
